# Generated by Django 5.1.5 on 2025-02-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "account",
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="account.account",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("date_opened", models.DateField(auto_now=True)),
            ],
        ),
    ]
