# Generated by Django 5.1.5 on 2025-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="date_opened",
            field=models.DateField(auto_now_add=True),
        ),
    ]
