# Generated by Django 5.1.5 on 2025-02-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_useraccount_date_opened"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="account",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="useraccount",
            table="useraccount",
        ),
        migrations.CreateModel(
            name="MultiPurposeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.IntegerField()),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.multipurposerecord",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "entries",
                "db_table": "entry",
            },
        ),
        migrations.CreateModel(
            name="SoloRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.useraccount",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Account",
        ),
    ]
