# Generated by Django 5.1.5 on 2025-02-06 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_useraccount_account_useraccount_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="record",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="solorecord",
            name="user_account",
        ),
        migrations.AddField(
            model_name="entry",
            name="value",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.IntegerField()),
                (
                    "useraccount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "userdata",
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="userdata",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.userdata",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="MultiPurposeRecord",
        ),
        migrations.DeleteModel(
            name="SoloRecord",
        ),
    ]
