# Generated by Django 5.1.5 on 2025-02-06 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_entry_record_remove_solorecord_user_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="userdata",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="account.userdata"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="useraccount",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="account.useraccount"
            ),
        ),
    ]
