# Generated by Django 5.1.5 on 2025-02-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_alter_entry_userdata_alter_userdata_useraccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="userdata",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.userdata"
            ),
        ),
        migrations.AlterField(
            model_name="userdata",
            name="useraccount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.useraccount"
            ),
        ),
    ]
