# Generated by Django 5.1.5 on 2025-02-06 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_entry_userdata_alter_userdata_useraccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdata",
            name="phone",
            field=models.CharField(
                help_text="+234-0000 or 0<your phone number>",
                max_length=15,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be in the format shown",
                        regex="^\\+?(\\d{1,3})?(\\d{10})$",
                    )
                ],
            ),
        ),
    ]
